version: '3.8'

services:
  agent:
    image: portainer/agent:2.13.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M

  portainer:
    image: portainer/portainer-ce:2.13.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
          - node.labels.hetzner_location == nbg1
      labels:
        - "traefik.docker.network=traefik-public"
        
        - "traefik.enable=true"
        - "traefik.http.routers.portainer-frontend.rule=Host(`portainer.example.tld.localhost`)"
        - "traefik.http.routers.portainer-frontend.entrypoints=http"
        - "traefik.http.services.portainer-frontend.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer-frontend.service=portainer-frontend"

        - "traefik.constraint-label=traefik-public"

networks:
  agent_network:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: ""
  traefik-public:
    external: true


volumes:
  portainer_data:
    driver: hetzner-volume
    driver_opts:
      size: '10'
      fstype: ext4
