---
- hosts: docker_swarm
  become: true
  vars:
    ansible_ssh_private_key_file: "{{ global_ansible_ssh_private_key_file | default((project_base_dir | default(playbook_dir)) + '/ssh_keys/ansible_rsa') }}"
    ansible_user: "{{ global_ansible_user | default('ansible') }}"
  roles:
    # copy the ssl certs from the beginning so all nodes have the certs on the system
    # so all mounts work
    - docker-swarm-hetzner-init-variables
    - copy-ssl-certs
    - docker-sysctl-tune
    - docker-pre-setup
    - docker-setup
    - docker-post-setup
    - docker-login
    - ufw-docker-install
    - docker-swarm-firewall
    - docker-swarm-hosts

- hosts: docker_swarm_manager
  become: true
  vars:
    ansible_ssh_private_key_file: "{{ global_ansible_ssh_private_key_file | default((project_base_dir | default(playbook_dir)) + '/ssh_keys/ansible_rsa') }}"
    ansible_user: "{{ global_ansible_user | default('ansible') }}"
  roles:
    - docker-swarm-hetzner-init-variables
    - docker-swarm-init
    - docker-swarm-add-manager

- hosts: docker_swarm_worker
  become: true
  vars:
    ansible_ssh_private_key_file: "{{ global_ansible_ssh_private_key_file | default((project_base_dir | default(playbook_dir)) + '/ssh_keys/ansible_rsa') }}"
    ansible_user: "{{ global_ansible_user | default('ansible') }}"
  roles:
    - docker-swarm-hetzner-init-variables
    - docker-swarm-add-worker

- hosts: docker_swarm
  become: true
  vars:
    ansible_ssh_private_key_file: "{{ global_ansible_ssh_private_key_file | default((project_base_dir | default(playbook_dir)) + '/ssh_keys/ansible_rsa') }}"
    ansible_user: "{{ global_ansible_user | default('ansible') }}"
  roles:
    - docker-swarm-hetzner-init-variables
    - docker-swarm-labels
