all:
  children:
    docker_swarm_manager:
      hosts:
        example-swarm-example-01:
          docker_swarm_advertise_addr: 192.168.0.2
          ansible_host: ip1
          host_ip: "{{ ansible_host }}"

          docker_swarm_labels:
            host: "example-swarm-example-01"
            hetzner_location: "nbg1"

          # required for paths inside the hetzner volumes
          # (e.g. if we share volumes in a service and subdivide the volume)
          # no need to do this if a whole volume is used by only one service
          docker_volumes: []
        example-swarm-example-02:
          docker_swarm_advertise_addr: 192.168.0.4
          ansible_host: ip2
          host_ip: "{{ ansible_host }}"

          docker_swarm_labels:
            host: "example-swarm-example-02"
            hetzner_location: "fsn1"

        example-swarm-example-03:
          docker_swarm_advertise_addr: 192.168.0.3
          ansible_host: ip3
          host_ip: "{{ ansible_host }}"

          docker_swarm_labels:
            host: "example-swarm-example-03"
            hetzner_location: "fsn1"


    docker_swarm_worker:
      # we want a HA swarm plane, so at least 3 managers
      hosts: {}
    docker_swarm:
      hosts:
        example-swarm-example-01:        
          docker_swarm_advertise_addr: 192.168.0.2
          ansible_host: ip1
          host_ip: "{{ ansible_host }}"

        example-swarm-example-02:
          docker_swarm_advertise_addr: 192.168.0.4
          ansible_host: ip2
          host_ip: "{{ ansible_host }}"

        example-swarm-example-03:
          docker_swarm_advertise_addr: 192.168.0.3
          ansible_host: ip3
          host_ip: "{{ ansible_host }}"