---
- name: populate labels dict
  set_fact:
    __labels: "{{ __labels| default({}) | combine( {'ansible_group_' + item: '1'} ) }}"
  with_items:
    - "{{ group_names }}"

- name: "add host defined labels"
  set_fact:
    __labels: "{{ __labels| default({}) | combine(docker_swarm_labels | default({})) }}"

- name: set docker swarm labels
  docker_node:
    labels: "{{ __labels }}"
    labels_state: replace
    hostname: "{{ inventory_hostname }}"
